# Default values for dotnet
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.

replicaCount: 1
restartPolicy: Never

# Evaluated by the post-install hook
sleepyTime: "10"

index: >-
  <h1>Hello</h1>
  <p>This is a test</p>

image:
  repository: microsoft/dotnet-samples
  tag: aspnetapp
  pullPolicy: IfNotPresent

service:
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: ClusterIP
  port: 80
  nodePort: ""

podAnnotations: {}

resources: {}

nodeSelector: {}
